site_name: Notes # Change this to your site name
site_description: A cool description of your site
site_url: https://eagleflag88.github.io/notes.github.io/ # Change this to your site URL

theme:
    name: 'material'
    logo: assets/meta/AD.jpeg
    favicon: assets/meta/AD.jpeg
    custom_dir: overrides
    font:
        text: Roboto
        code: Roboto Mono
    language: en
    palette:

    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: light blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
    features:
        - navigation.indexes
        - navigation.top
        - navigation.tabs
        - navigation.tabs.sticky
        - navigation.expand
        - search.suggest
        - search.highlight

nav:
  - Home: index.md
  - Deep Learning:
    - Basics: 
      - Normalization: Normalization.md
      - Loss: Loss.md
      - Training: Training.md
      - Evaluation: Evaluation.md
    - CNN:
      - Basics: CNN Basics.md
      - 2015-ResNet: 2015-ResNet.md
      - 2015-U-Net: 2015-UNet.md
      - 2017-Deformable Convolution: 2017-Deformable Convolution.md
      - 2017-FPN: 2017-Feature Pyramid Networks.md
      - 2017-MobileNet: 2017-MobileNet.md
      - 2017-ShuffleNet: 2017-ShuffleNet.md
      - 2019-EfficientNet: 2019-EfficientNet.md
      - 2022-ConvNeXt: 2022-ConvNeXt.md
    - Transformer:
      - Basics: Transformer Basics.md
      - 2020-ViT: 2020-ViT.md
      - 2021-Swin Transformer: 2021-Swin-Transformer.md
    - Detection:
      - 2016-Faster R-CNN: 2016-Faster R-CNN.md
      - 2019-FCOS: 2019-FCOS.md
      - 2020-EfficientDet: 2020-EfficientDet.md
      - 2021-Deformable Detr: 2021-Deformable Detr.md
      - 2021-YoloV5: 2021-YoloV5.md
      - 2022-RTMDet: 2022-RTMDet.md
    - BEV:
      - 2020-LSS: 2020-LSS.md
      - 2022-BEVDet: 2022-BEVDet.md
      - 2022-BEVDistill: 2022-BEVDistill.md
      - 2022-BEVFormer: 2022-BEVFormer.md
      - 2022-BEVFusion: 2022-BEVFusion.md
      - 2022-SoloFusion: 2022-SoloFusion.md
    - NeRF:
      - Basics: NeRF Basics.md
      - 2020-NeRF Representing Scenes as Neural Radiance Fields for View Synthesis: 2020-NeRF Representing Scenes as Neural Radiance Fields for View Synthesis.md
      - 2022-Instant-NGP: 2022-Instant-NGP.md
      - 2023-3D Gaussian Splatting for Real-Time Radiance Field Rendering: 2023-3D Gaussian Splatting for Real-Time Radiance Field Rendering.md
    - Software:
      - Pytorch: Pytorch.md
  - SLAM:
    - Basics: 
      - Camera Model: Camera Model.md
      - Transform: Transform.md
      - Lie Algebra: Lie Algebra.md
      - Outlier Rejection: Outlier Rejection.md
    - Front-End:
      - Motion Estimation: Motion Estimation.md
      - GNSS and IMU: GNSS and IMU.md
    - Back-End:
      - Pose Graph: Pose Graph.md
      - Bundle Adjustment: Bundle Adjustment.md
      - IMU Pre-Integration: IMU Pre-Integration.md
      - Factor Graph: Factor Graph.md
      - Marginalization: Marginalization.md
      - Estimator Consistency: Estimator Consistency.md
    - Software:
      - ceres: ceres.md
      - g2o: g2o.md
      - CMake: CMake.md
    - Lidar SLAM:
      - 2019-LIO-Mapping: 2019-LIO-Mapping.md
      - 2020-LIO-SAM: 2020-LIO-SAM.md
      - 2021-BALM: 2021-BALM.md
      - 2021-Fast-LIO2: 2021-Fast-LIO2.md
      - 2022-Faster-LIO: 2022-Faster-LIO.md
  - Math Basics:
    - Estimation:
      - State Estimation: State Estimation.md
      - Gaussian Filter: Gaussian Filter.md
      - Nonparametric Filter: Nonparametric Filter.md
      - Least Square Problem: Least Square Problem.md
    - Linear Algebra:
      - Matrix Decomposition: Matrix Decomposition.md
      - Solving Linear System: Solving Linear System.md
    - Optimization:
      - Numeric Optimization: Numeric Optimization.md
    - Assignment Problem: Assignment Problem.md  
  - Computer Science:
    - Python:
      - Âü∫Êú¨Ê¶ÇÂøµ: Âü∫Êú¨Ê¶ÇÂøµ-Python.md
      - Âü∫Êú¨Êï∞ÊçÆÁ±ªÂûã: Âü∫Êú¨Êï∞ÊçÆÁ±ªÂûã.md
      - ÂÖ≥ÈîÆÂ≠ó: ÂÖ≥ÈîÆÂ≠ó.md
      - Function: Function.md
      - Class: Class.md
      - Module: Module.md
      - Â§ö‰ªªÂä°Ê®°Âºè: Â§ö‰ªªÂä°Ê®°Âºè.md
      - ÂÜÖÂ≠òÁÆ°ÁêÜ: ÂÜÖÂ≠òÁÆ°ÁêÜ.md
    - C++:
      - Âü∫Êú¨Ê¶ÇÂøµ: 00-Âü∫Êú¨Ê¶ÇÂøµ-C++.md
      - Â§öÊÄÅ: Â§öÊÄÅ.md
      - Êô∫ËÉΩÊåáÈíà: Êô∫ËÉΩÊåáÈíà.md
      - Â∫èÂàóÂºèÂÆπÂô®: Â∫èÂàóÂºèÂÆπÂô®.md
      - ÂÖ≥ËÅîÂºèÂÆπÂô®: ÂÖ≥ËÅîÂºèÂÆπÂô®.md
      - ËÆæËÆ°Ê®°Âºè: ËÆæËÆ°Ê®°Âºè.md
      - Âπ∂ÂèëÁºñÁ®ã: Âπ∂ÂèëÁºñÁ®ã.md
    - Basics:
      - Êï∞ÊçÆÁªìÊûÑ: Êï∞ÊçÆÁªìÊûÑ.md
  - Paper Reading:
    - Online HDMap Construction:
      - 2022-HDMapNet: 2022-HDMapNet An Online HD Map Construction and Evaluation.md
      - 2022-VectorMapNet: 2022-VECTORMAPNET END-TO-END VECTORIZED HD MAP LEARNING.md
      - 2023-MapTRV1: 2023-MAPTR STRUCTURED MODELING AND LEARNING FOR ONLINE VECTORIZED HD MAP CONSTRUCTION.md
      - 2023-MapTRv2: 2023-MapTRv2 An End-to-End Framework for Online Vectorized HD Map Construction.md
      - 2023-BeMapNet: 2023-End-to-End Vectorized HD-Map Construction With Piecewise Bezier Curve.md
      - 2023-MachMap: 2023-MachMap End-to-End Vectorized Solution for Compact HD-Map Construction.md
      - 2023-MapVR: 2023-Online Map Vectorization for Autonomous Driving A Rasterization Perspective.md
      - 2023-StreamMapNet: 2023-StreamMapNet.md
      - 2023-Neural Map Prior for Autonomous Driving: 2023-Neural Map Prior for Autonomous Driving.md
      - 2023-LaneSegNet: 2023-LaneSegNet.md
      - 2023-SMERF: 2023-Augmenting Lane Perception and Topology Understanding with Standard Definition Navigation Maps.md
      - 2024-Complementing Onboard Sensors with Satellite Maps A New Perspective for HD Map Construction: 2024-Complementing Onboard Sensors with Satellite Maps A New Perspective for HD Map Construction.md
      - 2024-MapEX: 2024-MapEX.md
      - 2024-P-MapNet: 2024-P-MapNet.md
      - 2024-MapQR: 2024-MapQR.md
    - Topology Reasoning:
      - 2023-TopoNet: 2023-TopoNet.md
      - 2023-TopoMLP: 2023-TopoMLP.md
    - Map Merging:
      - 2017-3D Map Merging on Pose Graphs: 2017-3D Map Merging on Pose Graphs.md
      - 2019-Crowd-sourced Semantic Edge Mapping for Autonomous Vehicles: 2019-Crowd-sourced Semantic Edge Mapping for Autonomous Vehicles.md
      - 2020-Kimera-Multi a System for Distributed Multi-Robot Metric-Semantic Simultaneous Localization and Mapping: 2020-Kimera-Multi a System for Distributed Multi-Robot Metric-Semantic Simultaneous Localization and Mapping.md
      - 2021-A General Framework for Lifelong Localization and Mapping in Changing Environment: 2021-A General Framework for Lifelong Localization and Mapping in Changing Environment.md
      - 2021-DARE-SLAM: 2021-DARE-SLAM Degeneracy-Aware and Resilient Loop Closing in Perceptually-Degraded Environments.md
      - 2021-Kimera-Multi: 2021-Kimera-Multi Robust, Distributed, Dense Metric-Semantic SLAM for Multi-Robot Systems.md
      - 2021-LT-mapper: 2021-LT-mapper A Modular Framework for LiDAR-based Lifelong Mapping.md
      - 2022-AutoMerge: 2022-AutoMerge A Framework for Map Assembling and Smoothing in City-scale Environments.md
      - 2022-Crowdsourced Road Semantics Mapping Based on Pixel‚ÄêWise Confdence Level: 2022-Crowdsourced Road Semantics Mapping Based on Pixel‚ÄêWise Confdence Level.md
      - 2022-Crowdsourcing-Based Indoor Semantic Map Construction and Localization Using Graph Optimization: 2022-Crowdsourcing-Based Indoor Semantic Map Construction and Localization Using Graph Optimization.md
      - 2022-LAMP 2.0: 2022-LAMP 2.0 A Robust Multi-Robot SLAM System for Operation in Challenging Large-Scale Underground Environments.md
      - 2023-A Lightweight High Definition Mapping Method Based on Multi-Source Data Fusion Perception: 2023-A Lightweight High Definition Mapping Method Based on Multi-Source Data Fusion Perception.md
      - 2023-Multi-Session, Localization-oriented and Lightweight LiDAR Mapping Using Semantic Lines and Planes: 2023-Multi-Session, Localization-oriented and Lightweight LiDAR Mapping Using Semantic Lines and Planes.md
      - 2023-Swarm-SLAM: 2023-Swarm-SLAM Sparse Decentralized Collaborative Simultaneous Localization and Mapping Framework for Multi-Robot Systems.md
      - 2023-VMA: 2023-VMA Divide-and-Conquer Vectorized Map Annotation System for Large-Scale Driving Scene.md
      - 2023-maplab 2.0: 2023-maplab 2.0 A Modular and Multi-Modal Mapping Framework.md
    - Detection:
      - 2023-Co-Detr: 2023-DETRs with Collaborative Hybrid Assignments Training.md
    - BEV:
      - 2022-BEVDepth: 2022-BEVDepth Acquisition of Reliable Depth for Multi-view 3D Object Detection.md
      - 2023-SparseBEV: 2023-SparseBEV.md
      - 2023-Fast-BEV: 2023-Fast-BEV.md
    - Point Cloud Registration:
      - 2020-Graduated Non-Convexity for Robust Spatial Perception From Non-Minimal Solvers to Global Outlier Rejection: 2020-Graduated Non-Convexity for Robust Spatial Perception From Non-Minimal Solvers to Global Outlier Rejection.md
      - 2020-TEASER: 2020-TEASER Fast and Certifiable Point Cloud Registration.md
      - 2021-CLIPPER: 2021-CLIPPER A Graph-Theoretic Framework for Robust Data Association.md
    - Lidar SLAM:
      - 2020-3D Lidar Mapping Relative Accuracy Automatic Evaluation Algorithm: 2020-3D Lidar Mapping Relative Accuracy Automatic Evaluation Algorithm.md
      - 2021-Ground-SLAM: 2021-Ground-SLAM.md

    


# Extensions
markdown_extensions:
  - footnotes
  - nl2br
  - attr_list
  - sane_lists
  - meta
  - smarty
  - tables
  - mdx_breakless_lists
  - def_list
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.magiclink
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight:
      use_pygments: true
      anchor_linenums: true
  - pymdownx.tasklist:
       custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - admonition
  - toc:
      permalink: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
plugins:
  - search
  - meta-descriptions
  - git-revision-date-localized:
      type: date
      fallback_to_build_date: true
      locale: en
      custom_format: "%A %d %B %Y"
      enable_creation_date: true
  - ezlinks:
        wikilinks: true
  - awesome-pages
  - embed_file:
      callouts: true
      custom-attributes: 'assets/css/custom_attributes.css'
  - custom-attributes:
      file: 'assets/css/custom_attributes.css'
  - tags:
      tags_file: tags.md
  - encryptcontent:
      title_prefix: 'üîê'
      summary: 'Private page'
      placeholder: 'Password'
      decryption_failure_message: 'Invalid password'
      encryption_info_message: "You don't have access to this page."
      search_index: 'encrypted'
      password_button: True
      password_button_text: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" height="1em" width="1em"><!--! Font Awesome Pro 6.1.1 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2022 Fonticons, Inc. --><path d="M416 32h-64c-17.67 0-32 14.33-32 32s14.33 32 32 32h64c17.67 0 32 14.33 32 32v256c0 17.67-14.33 32-32 32h-64c-17.67 0-32 14.33-32 32s14.33 32 32 32h64c53.02 0 96-42.98 96-96V128C512 74.98 469 32 416 32zM342.6 233.4l-128-128c-12.51-12.51-32.76-12.49-45.25 0c-12.5 12.5-12.5 32.75 0 45.25L242.8 224H32C14.31 224 0 238.3 0 256s14.31 32 32 32h210.8l-73.38 73.38c-12.5 12.5-12.5 32.75 0 45.25s32.75 12.5 45.25 0l128-128C355.1 266.1 355.1 245.9 342.6 233.4z"/></svg>'
  - callouts
  - glightbox
hooks:
  - overrides/hooks/on_page_markdown.py
  - overrides/hooks/on_env.py
  - overrides/hooks/on_files.py
extra_javascript:
  - https://cdn.jsdelivr.net/gh/ObsidianPublisher/assets@main/dist/javascript.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
extra_css:
    - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css
    - https://cdn.jsdelivr.net/gh/ObsidianPublisher/assets@main/dist/styles.css
    - assets/css/admonition.css
    - assets/css/custom_attributes.css
    - assets/css/customization.css
extra:
  SEO: assets/meta/SEO.png
  comments: false #disable comments globally
  generate_graph: true #generate the graph of the site
  attachments: 'assets/img' #path to the folder where the attachments are stored
  no-auto-h1: false #disable the automatic generation of h1 if no h1 is found
  blog_list:
    pagination: true #enable pagination
    pagination_message: true #display the message "Showing x posts out of y"
    pagination_translation: 'posts in' #message to display before the number of posts ; Add your own translation!
    no_page_found: "No pages found!" #message to display when no pages are found ; Add your own translation!
  hooks:
    strip_comments: true
    fix_heading: true
